# Welcome to Jekyll!
#

# Site settings
title: Fabrica Tattoo Bar
description: |
  Rua Euclides da Cunha, 163
  Vila Ema
  São José dos Campos
owner: Ocimar Felipe Costa # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: ocimabr@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fabricatattoobar.com.br" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/fabricatattbar
  #github: https://github.com/fabricatattoobar
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/fabricatattoobar
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://instagram.com/fabricatattoobar
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
